flowchart TD
subgraph DECADENTISMO
        1[ESTETISMO]
    end

subgraph ESTETISMO
        2[NASCE IN INGHILTERRA]
    end
    
subgraph DANNUNZIO
        1[ESTETISMO]
    end

subgraph PASCOLI
        1[ESTETISMO]
    end

subgraph FUTURISMO
        1[ESTETISMO]
    end