flowchart TD
    subgraph CHE COSA è L'INFORMATICA
        1[LINGUAGGI DI PROGRAMMAZIONE]
        2[IDE]
    end

    subgraph LINGUAGGI DI PROGRAMMAZZIONE
        1[COMPILATO]
        2[NON COMPILATO]
    end

    subgraph ALTRO ARGOMENTO
        4[ARGOMENTO COLLEGABILE]
        
    end

    subgraph ALTRA MATERIA
        3[COLLEGARSI CON ALTRE MATERIE]
        
    end
    