-- database: /home/arlotti/repositories/ssh_sync_5a/v2_ex_5M/music-store.db

-- ### SQL Queries
-- Instructions: rename the file cognome.sql

-- #### Part 1
-- 1. List all albums along with the artist name
SELECT albums.* , artists.name
FROM artists
JOIN albums;

-- 2. Find all tracks and their album names
SELECT tracks.id , tracks.name, albums.title as album_title
FROM tracks
JOIN albums ON tracks.album_id = albums.id;

-- 3. List all tracks with their genre and media type
SELECT tracks.id , tracks.name, genres.name AS generes , media_types.name AS media_type
FROM tracks
JOIN genres ON tracks.genre_id = genres.id
JOIN media_types ON tracks.media_type_id = media_types.id;

-- 4. Find the total number of tracks in each playlist
SELECT playlists.id , playlists.name, count(playlist_tracks.track_id) AS number_of_tracks
FROM playlist_tracks
JOIN playlists ON playlist_tracks.playlist_id = playlists.id
GROUP BY playlist_tracks.playlist_id;

-- 5. List all customers along with their support representative's name
SELECT customers.id, customers.first_name AS customers, customers.last_name, employees.first_name AS employees, employees.last_name
FROM customers
JOIN employees ON customers.support_rep_id = employees.id;

-- 6. Find the total amount spent by each customer
SELECT customers.id AS customers_id, customers.first_name AS customers,  customers.last_name AS last_name, SUM(invoices.total) AS total_spend
FROM invoices
JOIN customers ON invoices.customer_id = customers.id
GROUP BY customers.id;

-- 7. List all invoices along with the customer's name and the total amount
SELECT invoices.id, customers.first_name AS customers_name, customers.last_name AS customers_last_name, invoices.total
FROM invoices
JOIN customers ON invoices.customer_id = customers.id;
-- 8. Find the most expensive track
-- 9. List all employees and their managers
-- 10. Find the total number of tracks in each genre
-- #### Part 2
-- 1. Find the total sales for each album
-- 2. List all customers who have never made a purchase
-- 3. Find the most popular genre by the number of tracks sold
-- 4. List all employees along with the number of customers they support
-- 5. Find the average invoice total for each customer
-- 6. List all tracks that are part of more than one playlist
-- 7. Find the total number of tracks sold for each media type
-- 8. List all albums that have tracks in more than one genre
-- 9. Find the total revenue generated by each genre
-- 10. List all customers along with the total number of invoices they have
-- #### Part 3
-- 1. Find the top 5 customers who have spent the most money
-- 2. List all tracks that have never been sold
-- 3. Find the employee who supports the most customers
-- 4. Find the total revenue generated by each artist
-- 5. List the top 3 genres by total sales revenue
-- 6. List all employees who do not have any direct reports
-- 7. Find the total number of tracks sold for each album
-- 8. Query to find the names of tracks that have a unit price higher than the average unit price of all tracks
-- 9. Query to find the names of employees who earn more than the average salary of their department
-- 10. Find the names of customers along with the titles of albums they have purchased
