flowchart TD
    subgraph CHE COSA è L'INFORMATICA
        1[LINGUAGGI DI PROGRAMMAZIONE]
        2[IDE]
    end

    subgraph AMBIENTI DI SVILUPPO
        38[Installazione e configurazione di WSL:Windows Subsystem for Linux]
        39[IDE: Visual Studio Code]
        40[Installazione e configurazione delle estensioni essenziali di VS Code Python, Ruff, GitLens, Markdown All in One]
        41[Creazione di un account GitHub]
        42[Configurazione di Git con le proprie credenziali]
        43[Markdown per il README.md]
        44[Creazione di un repository]
        45[Git integrato nell'interfaccia di VS Code]

        39 --> 38
        39 --> 40
        42 --> 39
        44 --> 43
        39 --> 45
        45 --> 44
        44 --> 41

    end

    subgraph LINGUAGGI DI PROGRAMMAZZIONE
        1[COMPILATO]
        2[NON COMPILATO]
    end

    subgraph Python tipizzazione e Type Hinting
        4[tipizzazione dinamica]
        
    end

    subgraph .gitignore e Ambiente Virtuale
        5[requirements.txt]
        6[.gitignore]
        7[venv]
        8[GitHub]
    end
    
    subgraph Modello ER e Database
        9[diagramma ER]
        10[cardinalità 1:1 1:N N:N]
        11[Come si traduce una relazione]
        12[dal modello ER al codice SQL]
        13[la Normalizzazione e quali problemi risolve: anomalie]
        14[la differenza tra Prima Seconda e Terza Forma Normale]
        15[ruolo della Chiave Primaria e della Chiave Esterna]
    end

    subgraph SQL e Interazione con Python
        16[DDL]
        17[CREATE]
        18[DROP]
        19[DML]
        20[INSERT]
        21[SELECT]
        22[clausole]
        23[GROUP BY]
        24[HAVING]
        25[JOIN]
        26[LEFT JOIN]
        27[SQL Injection]
        28[i file .sqlite]
        
    
    end
    16 --> 17
    16 --> 18

    19 --> 20
    19 --> 21

    22 --> 23
    22 --> 24

    28 --> 16
    28 --> 19
    28 --> 22
    28 --> 25
    28 --> 26
    28 --> 27

    subgraph Architettura Web e Flask
        29[cartella instance in Flask]
        
    end

    subgraph HTTP API e Sicurezza
        37[come è organizzata la struttura di un progetto flask]
        30[a cosa serve il file __init__.py]
        31[interno della cartella app?]
        32[Cosa sono i Blueprint]
        33[Cos'è il Repository Pattern]
        34[perché separiamo le query SQL dalle route di Flask?]
        35[il motore di template Jinja2]
        36[il concetto di ereditarietà extends]

        37 --> 30
        37 --> 31
        37 --> 33
        37 --> 34
        37 --> 35
        32 --> 36
        35 --> 32
    end