flowchart TD
    A[INFORMATICA] --> B[che cosa e' l'informatica]

    A --> C[Linguaggi di Programmazione]
    C --> C1[Linguaggio Compilato e Interpretato]
    C --> C2[Linguaggio tipizzato e non tipizzato, il type Hinting di python]
    C --> C3[esecuzione del codice]
    C --> C4[come programmare IDE]
    C --> C5[moduli, librerie]
    C --> C6[ambiente virtuale]
    C --> C7[github]
    C --> C8[git]

    C --> P[python]
    P --> P1[Liste]
    P --> P2[Variabili]
    P --> P3[Tuple]
    P --> P4[Funzioni]
    P --> P5[If, Elif ed Else]
    P --> P6[For e While]
    P --> P7[il random nei computer]
    P --> P8[la peculiarita' della programmazione, Input e Output in python]
    P --> P9[tempo di esecuzione, prestazioni]

    A --> OOP[Programmazione orientata ad oggetti OOP Object-Oriented Programming]
    OOP --> O1[Classi, Oggetti ed Attributi]
    OOP --> O2[costruttore]
    OOP --> O3[metodi]
    OOP --> O4[attributi]
    OOP --> O5[l'incapsulamento]
    OOP --> O6[Sottoclassi / Ereditarieta' / Aggregazioni o classi Composte]
    OOP --> O7[Polimorfismo]
    OOP --> O8[Tipi di Associazioni tra classi distinte]
    OOP --> O9[l'UML Unified Modelling Language]

    A --> D[DATABASE]
    D --> D1[DBSM DataBase Managment System e NoSQL]
    D --> D2[SQL]
    D --> D3[diagramma ER]
    D --> D4[La Chiave Univoca, Foreing key e Primary key]
    D --> D5[Vincoli di Integrità]
    D --> D6[ACID]
    D --> D7[cosa fa una query]
    D --> D8[che tabelle va a intaccare]

    A --> W[Web]
    W --> W1[Client e Server]
    W --> W2[HTTP, API e Sicurezza]
    W --> W3[API e REST]
    W --> W4[Endpoint HTML]
    W --> W5[Form html]
    W --> W6[javascript]
    W --> W7[Il Web Server cosa fa]
    W --> W8[Il DB cosa fa]
    W --> W9[Interfaccia utente]
    W --> W10[CLI]
    W --> W11[Flask]
    W --> W12[Deployment rilascio di un codice]

    A --> S[Sicurezza]
    S --> S1[la sicurezza informatica]
    S --> S2[Sicurezza Autenticazione, Autorizzazione, Audit]

    A --> F[File e dati]
    F --> F1[cosa e' un file]

    A --> M[Approccio TOP DOWN e BOTTOM UP]
    A --> R[Analisi dei Requisiti]