flowchart LR
    subgraph RISPOSTA DA DARE ALL'ESAME
        1[PREAMBOLO: DOVE CI TROVIAMO]
        2[DOPO RISPOSTA ALLA DOMANDA]
        
    end

    subgraph ALTRO ARGOMENTO
        4[ARGOMENTO COLLEGABILE]
        
    end

    subgraph ALTRA MATERIA
        3[COLLEGARSI CON ALTRE MATERIE]
        
    end

    1 --> 2
    2 --> 3
    2 --> 4